multi_speaker: False

transformer:
    max_seq_len: 1000
    encoder_layer: 4
    encoder_head: 2
    encoder_hidden: 256
    decoder_layer: 6
    decoder_head: 2
    decoder_hidden: 256
    conv_filter_size: 1024
    conv_kernel_size: [9, 1]
    encoder_dropout: 0.2
    decoder_dropout: 0.2

variance_adaptor:
    filter_size: 256
    kernel_size: 3
    dropout: 0.5
    n_bins: 256
